name: rgi
services:
  mongo:
    image: mongo:8.0-rc
    container_name: rgi_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local